## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` library.

In [9]:
import random

#### In the cell below, create a list named `sample_list_1` with 80 random values. 

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [10]:
sample_list_1 = random.sample(range(100), 80)
print(sample_list_1)

[2, 93, 5, 64, 71, 50, 66, 87, 21, 29, 41, 24, 97, 17, 16, 38, 75, 82, 8, 49, 25, 65, 33, 98, 67, 36, 15, 9, 55, 14, 52, 61, 68, 46, 23, 19, 54, 27, 95, 4, 28, 40, 42, 89, 63, 12, 1, 0, 78, 69, 31, 37, 91, 34, 86, 94, 51, 44, 18, 79, 53, 47, 73, 45, 59, 88, 20, 60, 11, 35, 22, 99, 72, 48, 90, 39, 32, 57, 84, 6]

#### Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [57]:
set1 = set(sample_list_1)
print(len(set1))
print(set1)
# As far as the population has unique elements, the elements selected by random will be also unique.

80
{0, 1, 2, 4, 5, 6, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 75, 78, 79, 82, 84, 86, 87, 88, 89, 90, 91, 93, 94, 95, 97, 98, 99}

#### Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop and the `randrange()` function.*

In [27]:
sample_list_2 = []

for i in range(80):
    sample_list_2.append(random.randrange(100))

print(sample_list_2)

[96, 6, 61, 63, 29, 56, 53, 6, 4, 72, 16, 86, 71, 31, 11, 36, 21, 44, 53, 27, 64, 22, 2, 3, 24, 96, 77, 72, 32, 23, 15, 14, 80, 1, 69, 9, 11, 41, 66, 84, 56, 1, 62, 19, 94, 33, 81, 41, 24, 80, 18, 70, 26, 47, 27, 95, 77, 84, 91, 76, 42, 65, 14, 51, 54, 37, 51, 6, 2, 79, 66, 53, 36, 88, 61, 73, 0, 11, 65, 98]

#### Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [28]:
set2 = set(sample_list_2)
len(set2)

57

#### Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [29]:
set3 = set1 - set2
print(set3)

{5, 8, 12, 17, 20, 25, 28, 34, 35, 38, 39, 40, 45, 46, 48, 49, 50, 52, 55, 57, 59, 60, 67, 68, 75, 78, 82, 87, 89, 90, 93, 97, 99}

#### Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [30]:
set4 = set2 - set1
print(set4)

{96, 3, 70, 76, 77, 80, 81, 56, 26, 62}

#### Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [31]:
set5 = set1.intersection(set2)
print(set5)

{0, 1, 2, 4, 6, 9, 11, 14, 15, 16, 18, 19, 21, 22, 23, 24, 27, 29, 31, 32, 33, 36, 37, 41, 42, 44, 47, 51, 53, 54, 61, 63, 64, 65, 66, 69, 71, 72, 73, 79, 84, 86, 88, 91, 94, 95, 98}

#### What is the relationship among the following values:

* len(set1)
* len(set2)
* len(set3)
* len(set4)
* len(set5)

Think about the set operations that you used to create the sets and how the lengths of the sets are related to each other given those operations.

In [38]:
len(set1) + len(set2) == len(set3) + len(set4) + 2*len(set5)

True

#### Create an empty set called `set6`.

In [43]:
set6 = set()
print(set6)
print(type(set6))

set()
<class 'set'>

#### Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [48]:
set6.update(set3)
set6.update(set5)

print(set6)

{0, 1, 2, 4, 5, 6, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 75, 78, 79, 82, 84, 86, 87, 88, 89, 90, 91, 93, 94, 95, 97, 98, 99}

#### Check if `set1` and `set6` are equal.

In [49]:
set1 == set6

True

#### Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.

In [52]:
set2.issubset(set1)

False

In [53]:
set3.issubset(set1)

True

#### Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`. 

#### Check if the aggregated values are equal.

In [54]:
set3.union(set4, set5) == set1.union(set2)

True

#### Using the `pop` method, remove the first element from `set1`.

In [56]:
set1.pop()

0

#### Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [58]:
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
for i in list_to_remove:
    set1.discard(i)

print(set1)

{0, 2, 4, 5, 6, 8, 12, 14, 15, 16, 17, 18, 20, 22, 23, 24, 25, 27, 28, 32, 33, 34, 35, 36, 37, 38, 40, 42, 44, 45, 46, 47, 48, 50, 52, 53, 54, 55, 57, 60, 63, 64, 65, 66, 67, 68, 72, 73, 75, 78, 82, 84, 86, 87, 88, 90, 93, 94, 95, 97, 98}